name: Research Website
markdown: kramdown
plugins:
  - jekyll-sitemap

# defaults:
#   -
#     scope:
#       path: ""  # empty string here means all files in project
#       type: "posts"
#     values:
#       layout: "default"
#   -
#     scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: "my-site"
#   -
#     scope:
#       path: "projects"
#       type: "pages" # previously `page` in Jekyll 2.2.
#     values:
#       layout: "project" # overrides previous default layout
#       author: "Mr. Hyde"

